<?php

class InsertImageCommand extends AbstractCommand
{
    /** @var ImageInterface */
    private $image;
    /** @var int */
    private $position;
    /** @var array */
    private $items = [];

    public function __construct($items, Image $image, int $position)
    {
        if ($position < -1) {
            echo "Wrong position";
        }
        $this->position = $position;
        $this->items = $items;
        $this->image = $image;
    }

    public function execute()
    {
        parent::execute(); // TODO: Change the autogenerated stub
    }

    public function unexecute()
    {
        parent::unexecute(); // TODO: Change the autogenerated stub
    }

    public function destroy()
    {
        $this->image->getController()->delete($this->image->getPath());
    }
}