<?php

class DocumentItem extends ConstDocumentItem
{
    public function getImage(): ImageInterface
    {
        parent::getImage(); // TODO: Change the autogenerated stub
    }

    public function getParagraph(): ParagraphInterface
    {
        parent::getParagraph(); // TODO: Change the autogenerated stub
    }
}