<?php
require_once __DIR__ . '/../behaviors/fly/IFlyBehavior.php';
require_once __DIR__ . '/../behaviors/fly/FlyWithWings.php';
require_once __DIR__ . '/../behaviors/fly/FlyNoWay.php';
require_once __DIR__ . '/../behaviors/quack/IQuackBehavior.php';
require_once __DIR__ . '/../behaviors/quack/QuackBehavior.php';
require_once __DIR__ . '/../behaviors/quack/SqueakBehavior.php';
require_once __DIR__ . '/../behaviors/quack/MuteQuackBehavior.php';
require_once __DIR__ . '/../behaviors/dance/IDanceBehavior.php';
require_once __DIR__ . '/../behaviors/dance/NoDance.php';
require_once __DIR__ . '/../behaviors/dance/DanceWaltz.php';
require_once __DIR__ . '/../behaviors/dance/DanceMinuet.php';
require_once __DIR__ . '/../Duck.php';
require_once __DIR__ . '/../DecoyDuck.php';
require_once __DIR__ . '/../RedheadDuck.php';
require_once __DIR__ . '/../RubberDuck.php';
require_once __DIR__ . '/../MillardDuck.php';
require_once __DIR__ . '/../ModelDuck.php';
require_once __DIR__ . '/../SimUDuck.php';