<?php

class Rectangle extends Shape
{
    public function draw(CanvasInterface $canvas)
    {
        parent::draw($canvas); // TODO: Change the autogenerated stub
    }

    public function getColor()
    {
        parent::getColor(); // TODO: Change the autogenerated stub
    }

}